### ISSUE TITLE
`findDomRefAtPos` returns the parentNode instead of the first child, when offset == 0

### ISSUE THREAD

**Issue by 5id** [atlassian/prosemirror-utils#26]
```
export const findDomRefAtPos = (position, domAtPos) => {
  const dom = domAtPos(position);
  if (dom.offset > 0) {
    return dom.node.childNodes[dom.offset - 1];
  }
  return dom.node;
};
```

Afaik `dom.offset` should always be used to access the child node.
i.e. this should instead look like:
```
export const findDomRefAtPos = (position, domAtPos) => {
  const dom = domAtPos(position);
  return dom.node.childNodes[dom.offset];
};
```

This lines up with it's the JS API in https://developer.mozilla.org/en-US/docs/Web/API/Range/setStart

It looks like may only affects nodes where the position is at the start of the first child node in a document.

**Comment by eshvedai** [comment]
The problem is in `domAtPos` that expects `start` position instead of position before the node, therefore `const dom = domAtPos(position);` will always give you incorrect DOM node.

If you have a document:
```
doc
-- [0]p
----[1]t[2]e[3]x[4]t[5]
--/p[6]
/doc
```
domAtPos(1) returns the paragraph, where 1 is the start position of the `p`.

**Comment by 5id** [comment]
domAtPos actually expects the position directly before the node. It expects that we **always** use offset to calculate the dom-node in question to look at

In your example:
```
doc
-- [0]p
----[1]t[2]e[3]x[4]t[5]
--/p[6]
/doc
```
with HTML
```html
<div class="ProseMirror">
  <p>
    text
  </p>
</div>
```

---
### domAtPos(0)
```js
const { node, offset } = domAtPos(0);
// node === '<div.ProseMirror/>'
// offset  === 0
// node.childNodes[offset] === '<p>'
```
---
### domAtPos(1)
```js
const { node, offset } = domAtPos(1);
// node === '<p>'
// offset  === 0
// node.childNodes[offset] === 'text'
```
---

This way, domAtPos(1) refers to the same PM object that nodeAt(1) gets, i.e.:
```js
const node = doc.nodeAt(0) // node.type === paragraph
const dom = domAtPos(0) // dom.node.childNodes[dom.offset] === 'p'
```

**Comment by eshvedai** [comment]
In this case if `offset > 1` (position somewhere inside of the node) it would return `undefined`, e.g. `view.domAtPos(2).node.childNodes[1]` in the example above. Maybe we should ignore the offset if `node` is a text node.
