### ISSUE TITLE
Add Create Table Method

### ISSUE THREAD

**Issue by jefrydco** [atlassian/prosemirror-utils#28]
Hi @eshvedai thanks for working on this utils, is there any chance to add create table method since I also have used prosemirror-table plugin but there is no create table method there. Luckily I found this repo but it seems there is no create table method here as well.

**Comment by eshvedai** [comment]
Sure, why not. I was planning to do it anyways 🙂will do it soon

**Comment by eshvedai** [comment]
released under `0.4.4`
