### ISSUE TITLE
findDomRefAtPos gives incorrect DOM node ref when there's a widget decoration

### ISSUE THREAD

**Issue by eshvedai** [atlassian/prosemirror-utils#38]
Apparently ProseMirror ignores decorations while calculating the offset inside `domAtPos` http://prosemirror.net/docs/ref/#view.EditorView.domAtPos

**Comment by 5id** [comment]
Is this not a bug in Prosemirror itself & should we be raising this against PM itself?

**Comment by eshvedai** [comment]
yeah, that's just a quick fix until it is fixed in PM as usually it takes some time.
