### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by zfha** [atlassian/prosemirror-utils#72]
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.npm.taobao.org/prosemirror-utils/download/prosemirror-utils-0.8.3.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/zhoufan/Documents/bmatch/youkeda-bops-vue/yarn-error.log".

**Comment by RatoX** [comment]
Hey @zfha this doesn't seems a problem anymore, I'm closing this issue for now, if you still having an issue please open a new issue.

Thank you
