### ISSUE TITLE
Update prosemirror-tables to 1.0.0

### ISSUE THREAD

**Issue by pmairoldi** [atlassian/prosemirror-utils#85]
Please update "prosemirror-tables" to latest (v.1.0.0).
Thanks.

**Comment by kfields** [comment]
If you could update all the prosemirror dependencies in package.json that would be super awesome!
Thanks!!!

**Comment by jscaux** [comment]
Another polite plea to update the package as soon as possible! Getting error and broken functionality because of this.

**Comment by Peter-Krebs** [comment]
Corrected in tiptap@1.26.7, tiptap-extensions@1.28.7
https://github.com/scrumpy/tiptap/issues/305#issuecomment-607412176 (also applies to npm install)

**Comment by RatoX** [comment]
There is no more `prosemirror-tables` dependency!

Thank you!
