### ISSUE TITLE
npm warning

### ISSUE THREAD

**Issue by holtwick** [atlassian/prosemirror-utils#87]
npm issues the following warning:

```
npm WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 but none is installed. You must install peer dependencies yourself.
```

Related to:
https://github.com/atlassian/prosemirror-utils/blob/64b258de4cfb28a1f34bfc66791db8520984d5e1/package.json#L67

prosemirror-tables is on 1.0.0. Maybe cahnging to:

```
 "prosemirror-tables": ">=0.9.1",
```

makes sense?

**Comment by RatoX** [comment]
There is no more `prosemirror-tables` dependency!

Thank you!
