### ISSUE TITLE
findSelectedNodeOfType() return type doesn't match documentation

### ISSUE THREAD

**Issue by twig-atl** [atlassian/prosemirror-utils#96]
missing `start` attribute

https://github.com/atlassian/prosemirror-utils/blob/e8e648bd591bae8bac10427e3b50caee3040e1d5/src/selection.js#L109

https://github.com/atlassian/prosemirror-utils/blob/e8e648bd591bae8bac10427e3b50caee3040e1d5/src/selection.js#L120-L127

**Comment by RatoX** [comment]
Thank you for your contribution. I fixed this problem when I migrated the project to TypeScript
